name: BlueFriends
version: 1.0.0
main: cn.bluesadi.bluefriends.BlueFriends
softdepend:
  - VexView
  - ProtocolLib
  - PlaceholderAPI
authors: [bluesadi]
commands:
  bfreload:
  friend:
  bfopen:
  bfadmin:
  person:
